Fix example server and add use gpu instruction in readme
PABannier/bark.cpp pull request #185
Opened 2024-07-15 02:22 UTC by goriri

2024-07-15 18:54 UTC, PABannier requested changes
Thank you for the PR @goriri ! I have a few comments regarding formatting and cleaning the codebase.

2024-07-15 18:54 UTC, PABannier commented on examples/server/server.cpp
> +// struct bark_params {
rm the comments if no longer used

2024-07-15 18:54 UTC, PABannier commented on examples/server/server.cpp
> +    {
We favour the curly braces on the same line as the statement. Please revert these changes.
```suggestion
    for (int i = 1; i < argc; i++) {
```

2024-07-15 18:54 UTC, PABannier commented on examples/server/server.cpp
> +        // generate audio
rm comments

2024-07-17 04:13 UTC, goriri commented on examples/server/server.cpp
> +        // generate audio
Fixed all these as requested.

2024-07-17 07:35 UTC, merged

2024-07-17 07:35 UTC, PABannier commented
@goriri Thanks for the PR! :)